matrix:
  include:
    - language: java
      jdk: openjdk8
      sudo: false
      script:
        - cd webservice && mvn clean verify && mvn test
        
    - language: node_js
      node_js: 8
      script:
        - cd user-app && npm install && npm test
        - cd ../admin-web-app && npm install && npm test
        
before_deploy: 
  - echo 'ready P1?'

deploy:
  - provider: heroku
    api_key:
      secure: "NL3g0U2tRWu2ekZcVkyYFNAMcwFzw9hFRBGdGNgU1VYIfo8P0jNhbdhh90Yf36gxwxnialaXD6vsa4JXNG81pygFqZJ59tN40scxxzHqXMe6lhLWslXuGiRRJl0NfWGG/E9JfV1mVBtCVVJonoOAc6Amq1tRMfk1dpFNZ1wXiznYKLRAhYHRQpJv6YMrbxBQ5ET/484abh77EzZszzpJ77hM6sglT4XKP+HH1P7xxYt8XVdVtftYpgVgSooVeCYxMxIBem4S20QyH2QsO83AJVA8s6cSUwlrbCu7Dpkcm410nqkS/eRts5dW3hTY6DRpvMVgJsPsXV8a55JNYjWz3f2W3lAe+h3rTCIDCZB4oPhZiavzkpLbimORAyfiPCDG64zLFz1VVtdT62WC8txjok9CvVft/nKio4dHx2Te0XQ0JOIFs8EZcfzootlYLPfWSEuDf61sadBpguBM97M/cDePyPBxmfMiyYldtTAtHF7MKcZvnBxFwZloikULWxREYms5G4L3qOsAFcDg1ItDrJQxNVlLgFj1y0V1Gi7sp93oMaFgFvmE51A8g2zw6LZmTcupp+nnwtZWNXfwwv42XYNYX+7ScpfmSUJ/8gMeV0IRq77dvpuRNLgSS88aeG6oP3wyggbauMcGWURVHqQlBx+4+HOLlOIom+tkG5ioQu0="
    app: asepartback
    on: 
      jdk: openjdk8
      all_branches: true
      tags: true
    skip_cleanup: true
  
  - provider: heroku
    api_key:
      secure: "NL3g0U2tRWu2ekZcVkyYFNAMcwFzw9hFRBGdGNgU1VYIfo8P0jNhbdhh90Yf36gxwxnialaXD6vsa4JXNG81pygFqZJ59tN40scxxzHqXMe6lhLWslXuGiRRJl0NfWGG/E9JfV1mVBtCVVJonoOAc6Amq1tRMfk1dpFNZ1wXiznYKLRAhYHRQpJv6YMrbxBQ5ET/484abh77EzZszzpJ77hM6sglT4XKP+HH1P7xxYt8XVdVtftYpgVgSooVeCYxMxIBem4S20QyH2QsO83AJVA8s6cSUwlrbCu7Dpkcm410nqkS/eRts5dW3hTY6DRpvMVgJsPsXV8a55JNYjWz3f2W3lAe+h3rTCIDCZB4oPhZiavzkpLbimORAyfiPCDG64zLFz1VVtdT62WC8txjok9CvVft/nKio4dHx2Te0XQ0JOIFs8EZcfzootlYLPfWSEuDf61sadBpguBM97M/cDePyPBxmfMiyYldtTAtHF7MKcZvnBxFwZloikULWxREYms5G4L3qOsAFcDg1ItDrJQxNVlLgFj1y0V1Gi7sp93oMaFgFvmE51A8g2zw6LZmTcupp+nnwtZWNXfwwv42XYNYX+7ScpfmSUJ/8gMeV0IRq77dvpuRNLgSS88aeG6oP3wyggbauMcGWURVHqQlBx+4+HOLlOIom+tkG5ioQu0="
    app: asepartback-dev
    on: 
      jdk: openjdk8
      all_branches: true
      tags: false
    skip_cleanup: true
    
  - provider: heroku
    api_key:
      secure: "NL3g0U2tRWu2ekZcVkyYFNAMcwFzw9hFRBGdGNgU1VYIfo8P0jNhbdhh90Yf36gxwxnialaXD6vsa4JXNG81pygFqZJ59tN40scxxzHqXMe6lhLWslXuGiRRJl0NfWGG/E9JfV1mVBtCVVJonoOAc6Amq1tRMfk1dpFNZ1wXiznYKLRAhYHRQpJv6YMrbxBQ5ET/484abh77EzZszzpJ77hM6sglT4XKP+HH1P7xxYt8XVdVtftYpgVgSooVeCYxMxIBem4S20QyH2QsO83AJVA8s6cSUwlrbCu7Dpkcm410nqkS/eRts5dW3hTY6DRpvMVgJsPsXV8a55JNYjWz3f2W3lAe+h3rTCIDCZB4oPhZiavzkpLbimORAyfiPCDG64zLFz1VVtdT62WC8txjok9CvVft/nKio4dHx2Te0XQ0JOIFs8EZcfzootlYLPfWSEuDf61sadBpguBM97M/cDePyPBxmfMiyYldtTAtHF7MKcZvnBxFwZloikULWxREYms5G4L3qOsAFcDg1ItDrJQxNVlLgFj1y0V1Gi7sp93oMaFgFvmE51A8g2zw6LZmTcupp+nnwtZWNXfwwv42XYNYX+7ScpfmSUJ/8gMeV0IRq77dvpuRNLgSS88aeG6oP3wyggbauMcGWURVHqQlBx+4+HOLlOIom+tkG5ioQu0="
    app: asepartweb
    on: 
      node: 8
      all_branches: true
      tags: true
    skip_cleanup: true
  
  - provider: heroku
    api_key:
      secure: "NL3g0U2tRWu2ekZcVkyYFNAMcwFzw9hFRBGdGNgU1VYIfo8P0jNhbdhh90Yf36gxwxnialaXD6vsa4JXNG81pygFqZJ59tN40scxxzHqXMe6lhLWslXuGiRRJl0NfWGG/E9JfV1mVBtCVVJonoOAc6Amq1tRMfk1dpFNZ1wXiznYKLRAhYHRQpJv6YMrbxBQ5ET/484abh77EzZszzpJ77hM6sglT4XKP+HH1P7xxYt8XVdVtftYpgVgSooVeCYxMxIBem4S20QyH2QsO83AJVA8s6cSUwlrbCu7Dpkcm410nqkS/eRts5dW3hTY6DRpvMVgJsPsXV8a55JNYjWz3f2W3lAe+h3rTCIDCZB4oPhZiavzkpLbimORAyfiPCDG64zLFz1VVtdT62WC8txjok9CvVft/nKio4dHx2Te0XQ0JOIFs8EZcfzootlYLPfWSEuDf61sadBpguBM97M/cDePyPBxmfMiyYldtTAtHF7MKcZvnBxFwZloikULWxREYms5G4L3qOsAFcDg1ItDrJQxNVlLgFj1y0V1Gi7sp93oMaFgFvmE51A8g2zw6LZmTcupp+nnwtZWNXfwwv42XYNYX+7ScpfmSUJ/8gMeV0IRq77dvpuRNLgSS88aeG6oP3wyggbauMcGWURVHqQlBx+4+HOLlOIom+tkG5ioQu0="
    app: asepartweb-dev
    on: 
      node: 8
      all_branches: true
      tags: false
    skip_cleanup: true

notifications:
    slack: amosss182:Jy3u9zaYLt3M9abd8PnYID3D 
